name: Test and Publish Docker Image

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t cargo-near .

      - name: Run tests in Docker container
        run: docker run -u $(id -u):$(id -g) --name cargo-near-container -v ${{ github.workspace }}/reproducible-test:/host cargo-near /bin/bash -c "/host/test.sh"

      - name: Calculate SHA hash of build output
        id: hash_output
        run: |
          docker cp cargo-near-container:/host/target/near/. /tmp/output
          wasm_file=$(ls /tmp/output/*.wasm | head -n 1)
          if [ -z "$wasm_file" ]; then
            echo "No WASM file found."
            exit 1
          fi
          sha_hash=$(sha256sum "$wasm_file" | awk '{ print $1 }')

  push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.result == 'success' }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract branch name
        id: branch_name
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_HUB_REPO }}
          tags: |
            type=raw,value=${{ env.branch }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
